config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index'

  get '/login', to: 'sessions#new', as: 'login_session'
  post '/login', to: 'sessions#create', as: 'create_session'
  delete '/logout', to: 'sessions#destroy', as: 'logout_session'

  get '/register', to: 'users#new', as: 'new_user'
  post '/register', to: 'users#create', as: 'create_user'
  get '/user/:id/make_admin', to: 'users#make_admin', as: 'make_admin'
  get '/user/:id/revoke_admin', to: 'users#revoke_admin', as: 'revoke_admin'
  get '/user/:id', to: 'users#show', as: 'show_user'
  get '/users', to: 'users#index', as: 'users'
  delete '/user/:id', to: 'users#destroy', as: 'delete_user'

  get '/stack/new', to: 'stacks#new', as: 'new_stack'
  post '/stack/new', to: 'stacks#create', as: 'create_stack'
  get '/stack/:id/edit', to: 'stacks#edit', as: 'edit_stack'
  patch '/stack/:id', to: 'stacks#update', as: 'update_stack'
  get '/stack/:id', to: 'stacks#show', as: 'show_stack'
  get '/stack/:id/join', to: 'stacks#join', as: 'join_stack'
  get '/stack/:id/leave', to: 'stacks#leave', as: 'leave_stack'
  get '/stack/:id/clue_tree', to: 'stacks#clue_tree', as: 'clue_tree'
  get '/stacks', to: 'stacks#index', as: 'stacks'
  delete '/stack/:id', to: 'stacks#destroy', as: 'delete_stack'

  get '/stack/:stack_id/new_clue', to: 'clues#new', as: 'new_clue'
  post '/stack/:stack_id/new_clue', to: 'clues#create', as: 'create_clue'
  get '/stack/:stack_id/:id/edit', to: 'clues#edit', as: 'edit_clue'
  post '/stack/:stack_id/:id/edit', to: 'clues#update', as: 'update_clue'
  get '/stack/:stack_id/:id', to: 'clues#show', as: 'show_clue'
  delete '/stack/:stack_id/:id', to: 'clues#destroy', as: 'delete_clue'

  get '/stack/:stack_id/:clue_id/new_solution', to: 'solutions#new', as: 'new_solution'
  post '/stack/:stack_id/:clue_id/new_solution', to: 'solutions#create', as: 'create_solution'
  get '/stack/:stack_id/:clue_id/:id', to: 'solutions#edit', as: 'edit_solution'
  post '/stack/:stack_id/:clue_id/:id', to: 'solutions#update', as: 'update_solution'
  delete '/stack/:stack_id/:clue_id/:id', to: 'solutions#destroy', as: 'delete_solution'

  get '/stack/:stack_id/current_objectives', to: 'assignments#current_objectives', as: 'current_objectives'
  get '/stack/:stack_id/finished_objectives', to: 'assignments#finished_objectives', as: 'finished_objectives'
end

app/models/stack.rb
class Stack < ApplicationRecord
  has_many :stackers, dependent: :nullify
  has_many :stackees, dependent: :nullify
  has_many :clues, dependent: :destroy

  validates :name, presence: true,
            uniqueness: true
end

app/controllers/stacks_controller.rb
class StacksController < ApplicationController
  def new
    logged_in_checker {
      current_user_is_stacker {
        @stack = Stack.new
      }
    }
  end

  def create
    logged_in_checker {
      current_user_is_stacker {
        @stack = Stack.new(stack_params)
        if @stack.save
          @current_user.update(type: 'Stacker', stack_id: @stack.id)
          redirect_to show_user_url(@current_user)
        else
          render 'new'
        end
      } 
    }
  end

  def edit
    logged_in_checker {
      @stack = Stack.find(params[:id])
      current_user_belongs_to_stack {}
    }
  end

  def update
    logged_in_checker {
      @stack = Stack.find(params[:id])
      current_user_belongs_to_stack {
        if @stack.update(stack_params)
          redirect_to show_stack_url(@stack)
        else
          render 'edit'
        end
      }
    }
  end

  def show
    logged_in_checker {
      @stack = Stack.find(params[:id])
      @user = current_user
      @stackers = @stack.stackers
      @stackees = @stack.stackees
    }
  end

  def join
    logged_in_checker {
      @stack = Stack.find(params[:id])
      current_user.update(stack_id: @stack.id)
      redirect_to show_user_url(@current_user)
    }
  end

  def leave
    logged_in_checker {
      @stack = Stack.find(params[:id])
      @user = current_user
      if @user.belongs_to_stack?(@stack.id)
        @user.update(stack_id: nil)
      end
      redirect_to show_user_url(@user)
    }
  end

  def clue_tree
    logged_in_checker {
      @stack = Stack.find(params[:id])
      if current_user.belongs_to_stack?(@stack.id) and current_user.stacker?
        @clues = @stack.clues
      else
        redirect_to show_user_url(@current_user)
      end
    }
  end

  def index
    logged_in_checker {
      @stacks = Stack.all
      @user = current_user
    }
  end

  def destroy
    logged_in_checker {
      called_by_admin {
        @stack = Stack.find(params[:id])
        @stack.destroy
        redirect_to stacks_url
      }
    }
  end

  private
    def current_user_belongs_to_stack
      if current_user.admin? or current_user.belongs_to_stack?(@stack.id)
        yield
      else
        redirect_to show_user_url(current_user)
      end
    end

    def stack_params
      params.require(:stack).permit(:name, :description)
    end
end

app/helpers/stacks_helper.rb
module StacksHelper
end

app/views/stacks/add_stacker.html.erb
<div id='page_title'>
  <h1>Add Stackers</h1>
</div>
<%= render 'shared/stack_info' %>
<% if @users.length > 0 %>
  <%= form_for @stack, url: update_stackers_path(@stack) do |f| %>
    <%= f.collection_check_boxes :user_ids, @users, :id, :name %>
    <%= f.submit 'Add to Stack' %>
  <% end %>
  <%= link_to 'Cancel', show_stack_path(@stack) %>
<% else %>
  <p>
    There are no available users to make into stackers.
    <%= link_to 'Go back.', show_stack_path(@stack) %>
  </p>
<% end %>

app/views/stacks/clue_tree.html.erb
<div id='page_title'>
  <h1>Clue Tree</h1>
</div>

<%= link_to 'Write a new clue', new_clue_path(stack_id: @stack) %>

<% @clues.each do |clue| %>
  <div class='clue_box'>
    <p>
      <%= link_to clue.title, show_clue_path(stack_id: @stack, id: clue) %>
    </p>
    <% if clue.next_clues.size > 0 %>
      <p>
        Leads to:<br>
        <% clue.next_clues.each do |next_clue| %>
          <%= link_to next_clue.title, show_clue_path(stack_id: @stack, id: next_clue) %><br>
        <% end %>
      </p>
    <% end %>
  </div>
<% end %>

<%= link_to 'Return to Stack Details', show_stack_path(@stack) %>

app/views/stacks/edit.html.erb
<div id='page_title'>
  <h1>Edit this Stack</h1>
</div>

<%= form_for @stack, url: update_stack_path do |f| %>
  <p>
    Stack Name:
    <%= f.text_field :name %>
  </p>
  <p>
    Description:
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit 'Update Stack' %>
    </p>
<% end %>

<%= link_to 'Cancel', show_stack_path(@stack) %>

app/views/stacks/index.html.erb
<div id='page_title'>
  <h1>List of Stacks</h1>
</div>

<% if !@user.stack_id and @user.stacker? %>
  <p>
    <%= link_to 'Create a Stack', new_stack_path %>
    or choose from existing ones.
  </p>
<% end %>

<table>
  <% @stacks.each do |stack| %>
    <tr>
      <td><%= stack.name %></td>
      <td><%= link_to 'See Details', show_stack_path(stack) %></td>
      <% if @user.admin? %>
        <td><%= link_to 'Delete this Stack',
                delete_stack_path(stack),
                method: :delete %></td>
      <% end %>          
    <tr>
  <% end %>
</table>
<%= render 'shared/tail' %>

app/views/stacks/new.html.erb
<div id='page_title'>
  <h1>Create a Stack</h1>
</div>

<p>
  Creating a stack will make you one of its Stackers.
</p>

<%= render 'shared/errors', container: @stack %>
<%= form_for @stack, url: create_stack_path do |f| %>
  <p>
    Stack Name:
    <%= f.text_field :name %>
  </p>
  <p>
    Description:
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit 'Create Stack' %>
    </p>
<% end %>

<%= link_to 'Cancel', stacks_path %>

app/views/stacks/show.html.erb
<div id='page_title'>
  <h1>Stack Details</h1>
</div>
<%= render 'shared/stack_info' %>
<% if @user.belongs_to_stack?(@stack.id) %>
  <% if @user.stacker? %>
    <%= link_to 'Edit this Stack', edit_stack_path(@stack) %>
    <%= link_to 'See the Clue Tree', clue_tree_path(@stack) %>
  <% elsif @user.stackee? %>
    <%= link_to 'See Current Objectives', current_objectives_path(@stack) %>
    <%= link_to 'See Finished Objectives', finished_objectives_path(@stack) %>
  <% end %>
  <%= link_to 'Leave this Stack', leave_stack_path(@stack) %>
<% elsif !@user.stack_id %>
  <%= link_to 'Join this Stack', join_stack_path(@stack) %>
  <%= link_to 'Return to List of Stacks', stacks_path %>
<% end %>  
<%= render 'shared/tail' %>