config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index'

  get '/login', to: 'sessions#new', as: 'login_session'
  post '/login', to: 'sessions#create', as: 'create_session'
  delete '/logout', to: 'sessions#destroy', as: 'logout_session'

  get '/register', to: 'users#new', as: 'new_user'
  post '/register', to: 'users#create', as: 'create_user'
  get '/user/:id/make_admin', to: 'users#make_admin', as: 'make_admin'
  get '/user/:id/revoke_admin', to: 'users#revoke_admin', as: 'revoke_admin'
  get '/user/:id', to: 'users#show', as: 'show_user'
  get '/users', to: 'users#index', as: 'users'
  delete '/user/:id', to: 'users#destroy', as: 'delete_user'

  get '/stack/new', to: 'stacks#new', as: 'new_stack'
  post '/stack/new', to: 'stacks#create', as: 'create_stack'
  get '/stack/:id/edit', to: 'stacks#edit', as: 'edit_stack'
  patch '/stack/:id', to: 'stacks#update', as: 'update_stack'
  get '/stack/:id', to: 'stacks#show', as: 'show_stack'
  get '/stack/:id/join', to: 'stacks#join', as: 'join_stack'
  get '/stack/:id/leave', to: 'stacks#leave', as: 'leave_stack'
  get '/stack/:id/clue_tree', to: 'stacks#clue_tree', as: 'clue_tree'
  get '/stacks', to: 'stacks#index', as: 'stacks'
  delete '/stack/:id', to: 'stacks#destroy', as: 'delete_stack'

  get '/stack/:stack_id/new_clue', to: 'clues#new', as: 'new_clue'
  post '/stack/:stack_id/new_clue', to: 'clues#create', as: 'create_clue'
  get '/stack/:stack_id/:id/edit', to: 'clues#edit', as: 'edit_clue'
  post '/stack/:stack_id/:id/edit', to: 'clues#update', as: 'update_clue'
  get '/stack/:stack_id/:id', to: 'clues#show', as: 'show_clue'
  delete '/stack/:stack_id/:id', to: 'clues#destroy', as: 'delete_clue'

  get '/stack/:stack_id/:clue_id/new_solution', to: 'solutions#new', as: 'new_solution'
  post '/stack/:stack_id/:clue_id/new_solution', to: 'solutions#create', as: 'create_solution'
  get '/stack/:stack_id/:clue_id/:id', to: 'solutions#edit', as: 'edit_solution'
  post '/stack/:stack_id/:clue_id/:id', to: 'solutions#update', as: 'update_solution'
  delete '/stack/:stack_id/:clue_id/:id', to: 'solutions#destroy', as: 'delete_solution'

  get '/stack/:stack_id/current_objectives', to: 'assignments#current_objectives', as: 'current_objectives'
  get '/stack/:stack_id/finished_objectives', to: 'assignments#finished_objectives', as: 'finished_objectives'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password

  validates :name, :presence => true
  validates :username, :presence => true,
                       :length => { :maximum => 18 },
		               :uniqueness => true
  validates :password, :confirmation => true
  validates :password, :presence => true, :on => :create

  before_save :encrypt_password

  def admin?
    # returns true if the user is an Admin
    type == 'Admin'
  end

  def stacker?
    # returns true if the user is a stacker
    type == 'Stacker'
  end

  def stackee?
    # returns true if the user is a stackee
    type == 'Stackee'
  end
 
  def belongs_to_stack?(id)
    # returns true if the user belongs to the stack with the given
    # id. false if the user does not or doesn't belong to a stack at all
    stack_id == id
  end

  def is_user?(other)
    id == other.id
  end

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.match_password(password)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def match_password(password)
    encrypted_password == BCrypt::Engine.hash_secret(password, salt)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # Registration page for new users
    not_logged_in_checker { @user = User.new }
  end

  def create
    # Registration attempt for new users
    not_logged_in_checker {
      @user = User.new(user_params)
      if @user.save
        redirect_to login_session_url
      else
        render 'new'
      end
    }
  end

  def make_admin
    # Upgrades a user to an admin. Does not affect stack affiliation
    logged_in_checker {
      called_by_admin {
        @user = User.find(params[:id])
        @user.update(type: 'Admin')
        redirect_to show_user_url
      }
    }
  end

  def revoke_admin
    # Removes admin privileges from the user. Returns them to stacker
    logged_in_checker {
      called_by_admin {
        @user = User.find(params[:id])
        @user.update(type: 'Stacker')
        redirect_to show_user_url
      }
    }
  end

  def show
    # User's Home
    logged_in_checker {
      @user = User.find(params[:id])
      if !@user.is_user?(current_user)
        # This page can only be shown to its owner or an admin
        called_by_admin {}
      end
      if @user.stack_id
        @stack = Stack.find(@user.stack_id)
      end
    }
  end

  def index
    logged_in_checker {
      called_by_admin {
        @users = User.all
      }
    }
  end

  def destroy
    logged_in_checker {
      called_by_admin {
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_url
      }
    }
  end

  private
    def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation, :type)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show_header.html.erb
<div id='page_title'>
  <h1>Home</h1>
</div>

<p>
  Welcome, <%= @user.name %>! Your username is <%= @user.username %>.
  You are a <%= @user.type %>.  
</p>

app/views/users/_show_tail.html.erb
<% if current_user.admin? %>
  <%= link_to 'Return to Index', users_path %>
<% end %>

app/views/users/index.html.erb
<h1>Users Index</h1>

<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, show_user_path(user) %></td>
      <td><%= user.type %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'shared/errors', container: @user %>
<%= form_for :user do |f| %>
  <p>
    Your Name<br>
    <%= f.text_field :name %>
  </p>
  <p>
    Are you a Stacker or Stackee?<br>
    <%= f.radio_button :type, 'Stacker' %> Stacker<br>
    <%= f.radio_button :type, 'Stackee' %> Stackee
  <p>
    Username<br>
    <%= f.text_field :username %>
  </p>
  <p>
    Password<br>
    <%= f.password_field :password %>
  </p>
  <p>
    Password confirmation<br>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit 'Sign Up' %>
  </p>
<% end %>

<%= link_to 'Or Login to an Existing Account', login_session_path %>

app/views/users/show.html.erb
<%= render 'show_header' %>
<% if @user.stack_id %>
  <p>
    Your stack's name is: <%= link_to @stack.name,
      show_stack_path(@stack) %>
  </p>
<% else %>
  <%= link_to 'Join a Stack!', stacks_path %>
<% end %>
<% if current_user.admin? && current_user != @user%>
  <p>Admin Actions:</p>  
  <%= link_to 'Delete this User',
      delete_user_path(@user),
      method: :delete %><br>
  <%= link_to 'Make this User an Admin',
      make_admin_path(@user) %><br>
<% end %>
<%= render 'show_tail' %>

app/views/users/showAdmin.html.erb
<%= render 'show_common' %>
<p>
  This user is an Admin
</p>
<% if current_user.admin? && current_user != @user %>
  <%= link_to 'Revoke Admin Privileges',
      revoke_admin_path(@user) %><br>
<% end %>
<%= render 'show_tail' %>